# Default configuration
# the development environment use configuration file [app.dev.yaml]
# the production environment use configuration file [app.prod.yaml]
# the environment configuration will merge with default configuration
server:
  domain: localhost
  port: 6636

database:
  default:
    type: mysql
    name: 
    host: 
    port: 
    username: 
    password: 
    charset:
    loc: 
  write:
    type: mysql
    name: 
    host: 
    port: 
    username: 
    password: 
    charset:
    loc: 
  read:
    type: mysql
    name: 
    host: 
    port: 
    username: 
    password: 
    charset:
    loc: 

wework:
  corp_id:
  agent_id:
  corp_secret:
  contacts_secret: Nc0Q4bxPPFI8pVANU2xbqod1JAWDANu0HUdEDo66_cc
  contacts_token: YDboX2dHBDGiDWoUVEt
  contacts_aeskey: 3xoJTM2sVT2WNxbmSZUnybLu3JvW9Ww21RzBGgHLJNL

github:
  build_token: